apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}-mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.name }}-mysql
  template:
    metadata:
      labels:
        app: {{ .Values.name }}-mysql
    spec:
      containers:
        - image: mysql
          imagePullPolicy: Always
          name: {{ .Values.name }}-mysql
          env:
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.name }}-mysql-secret
                  key: mysql-user
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.name }}-mysql-secret
                  key: mysql-password
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.name }}-mysql-secret
                  key: mysql-root-password
            - name: MYSQL_DATABASE
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.name }}-mysql-secret
                  key: mysql-database
          ports:
            - containerPort: 3306
              name: sql
          resources:
            requests:
              cpu: 100m
          volumeMounts:
            - name: mysql-persistent-storage
              mountPath: /var/lib/mysql
      volumes:
        - name: mysql-persistent-storage
          persistentVolumeClaim:
            claimName: {{ .Values.name }}-mysql-disk
---
apiVersion: v1
kind: Service
metadata:
  name: mysql
  labels:
    app: {{ .Values.name }}-mysql
spec:
  type: ClusterIP
  ports:
    - port: 3306
      targetPort: 3306
      protocol: TCP
  selector:
    app: {{ .Values.name }}-mysql
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.name }}-mysql-secret
type: Opaque
data:
  mysql-user: {{ .Values.dbuser | b64enc | quote }}
  mysql-password: {{ .Values.dbpass | b64enc | quote }}
  mysql-root-password: {{ .Values.dbpass | b64enc | quote }}
  mysql-database: {{ .Values.dbname | b64enc | quote }}
---


kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ .Values.name }}-mysql-disk
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi