apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Values.name }}-{{ .Values.uuid }}-db-init
spec:
  template:
    spec:
      containers:
      - name: db-init
        image: mattiashem/init
        env:
          - name: DEST_DBPASS
            valueFrom:
              secretKeyRef:
                name: {{ .Values.name }}-{{ .Values.uuid }}
                key: SQL_PASSWORD
          - name: DEST_DBUSER
            valueFrom:
              secretKeyRef:
                name: {{ .Values.name }}-{{ .Values.uuid }}
                key: SQL_USER
          - name: DEST_DB
            valueFrom:
              secretKeyRef:
                name: {{ .Values.name }}-{{ .Values.uuid }}
                key: SQL_USER
          - name: DBHOST
            value: {{ .Values.name }}-{{ .Values.uuid }}-mysql-master
          - name: DBPORT
            value: "{{ .Values.dbport }}"
          - name: ROOT
            value: "root"
          - name: ROOTPASS
            valueFrom:
              secretKeyRef:
                name: {{ .Values.name }}-{{ .Values.uuid }}
                key: ROOT_PASSWORD
          - name: SEED_DB
            value: "{{ .Values.seed }}"
          - name: SEED_SOURCE
            value: "{{ .Values.seedSource }}"

      restartPolicy: Never