kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ .Values.name }}-{{ .Values.uuid }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.storage }}
  storageClassName: {{ .Values.storageClass }}

