apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}-{{ .Values.uuid }}-redis-service
  labels:
    app: {{ .Values.name }}-{{ .Values.uuid }}-redis-pod
spec:
  ports:
    - port: 6379
      targetPort: 6379
      protocol: TCP
  selector:
    app: {{ .Values.name }}-{{ .Values.uuid }}-redis-pod