apiVersion: mysql.presslabs.org/v1alpha1
kind: MysqlCluster
metadata:
  name: {{ .Values.name }}-{{ .Values.uuid }}
spec:
  replicas: 1
  secretName: {{ .Values.name }}-{{ .Values.uuid }}
  mysqlVersion: "8.0"
  podSpec:
    resources:
      requests:
        cpu: 200m
        memory: 200Mi
      limits:
        cpu: 1000m
        memory: 1Gi
  volumeSpec:
    persistentVolumeClaim:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 20Gi