apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.name }}-{{ .Values.uuid }}
  annotations:
      {{-  range $key, $topping := $.Values.hosting.tags }}
      {{ $key }}: {{ $topping }}
      {{- end }}
type: Opaque
data:
  POSTGRES_PASSWORD: {{ .Values.dbpass | b64enc }}
  POSTGRES_USER: {{ .Values.dbuser | b64enc }}
  REDIS_PASSWORD: {{ .Values.redisPassword | b64enc }}
  JWT_SECRET: {{ .Values.jwtSecret | b64enc }}
  ANON_KEY: {{ .Values.anonKey | b64enc }}
  SERVICE_ROLE_KEY: {{ .Values.serviceRoleKey | b64enc }}
  RLS_CLIENT_PASSWORD: {{ .Values.rlsClientPassword | b64enc }}
  TYPESENSE_API_KEY: {{ .Values.typesenseApiKey | b64enc }}
  SECRET_KEY_BASE: {{ .Values.secretKeyBase | b64enc }}
  VAULT_ENC_KEY: {{ .Values.vaultEncKey | b64enc }}
  DASHBOARD_USERNAME: {{ .Values.dashboardUsername | b64enc }}
  DASHBOARD_PASSWORD: {{ .Values.dashboardPassword | b64enc }}
  SMTP_USER: {{ .Values.smtpUser | b64enc }}
  SMTP_PASS: {{ .Values.smtpPass | b64enc }}
