apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}-{{ .Values.uuid }}-typesense
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.name }}-{{ .Values.uuid }}-typesense
  template:
    metadata:
      labels:
        app: {{ .Values.name }}-{{ .Values.uuid }}-typesense
    spec:
      containers:
        - image: typesense/typesense:29.0
          imagePullPolicy: IfNotPresent
          name: typesense
          env:
            - name: TYPESENSE_API_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.name }}-{{ .Values.uuid }}
                  key: TYPESENSE_API_KEY
            - name: TYPESENSE_DATA_DIR
              value: /data
          ports:
            - containerPort: 8108
              name: http
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
          volumeMounts:
            - name: typesense-data
              mountPath: /data
      volumes:
        - name: typesense-data
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}-{{ .Values.uuid }}-typesense
  labels:
    app: {{ .Values.name }}-{{ .Values.uuid }}-typesense
spec:
  type: ClusterIP
  ports:
    - port: 8108
      targetPort: 8108
      protocol: TCP
  selector:
    app: {{ .Values.name }}-{{ .Values.uuid }}-typesense
